"""
Storage adapter for Memory class

This module provides an adapter that bridges the VectorStoreBase interface
with the interface expected by the Memory class.
"""

import logging
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from powermem.storage.base import VectorStoreBase
from powermem.utils.utils import serialize_datetime

logger = logging.getLogger(__name__)


class StorageAdapter:
    """Adapter that bridges VectorStoreBase interface with Memory class expectations."""
    
    def __init__(self, vector_store: VectorStoreBase, embedding_service=None):
        """Initialize the adapter with a vector store and embedding service."""
        self.vector_store = vector_store
        self.embedding_service = embedding_service
        # get collection name from vector store attribute collection_name
        self.collection_name = getattr(vector_store, 'collection_name', 'memories')

        # Ensure collection exists (will be created with actual vector size when first vector is added)
        # self.vector_store.create_col(self.collection_name, vector_size=1536, distance="cosine")
    
    def add_memory(self, memory_data: Dict[str, Any]) -> int:
        """Add a memory to the store."""
        # ID will be auto-generated by the database, no need to pre-generate
        
        # Create vector from content using embedding service
        content = memory_data.get("content", "")
        if self.embedding_service:
            try:
                vector = self.embedding_service.embed(content, memory_action="add")
                # Create collection with actual vector size if not exists
                if not hasattr(self, '_collection_created'):
                    self.vector_store.create_col(self.collection_name, vector_size=len(vector), distance="cosine")
                    self._collection_created = True
            except Exception as e:
                logger.warning(f"Failed to generate embedding, using mock vector: {e}")
                vector = [0.1] * 1536  # Use 1536 dimensions for OceanBase compatibility
                if not hasattr(self, '_collection_created'):
                    self.vector_store.create_col(self.collection_name, vector_size=1536, distance="cosine")
                    self._collection_created = True
        else:
            # Use 1536 dimensions for OceanBase compatibility
            vector = [0.1] * 1536
            if not hasattr(self, '_collection_created'):
                self.vector_store.create_col(self.collection_name, vector_size=1536, distance="cosine")
                self._collection_created = True
        
        # Store the memory data as payload - unified format based on OceanBase
        payload = {
            "data": content,  # Unified field name for text content
            "user_id": memory_data.get("user_id", ""),
            "agent_id": memory_data.get("agent_id", ""),
            "run_id": memory_data.get("run_id", ""),
            "actor_id": memory_data.get("actor_id", ""),
            "hash": memory_data.get("hash", ""),
            "created_at": serialize_datetime(memory_data.get("created_at", "")),
            "updated_at": serialize_datetime(memory_data.get("updated_at", "")),
            "category": memory_data.get("category", ""),
            "fulltext_content": content,  # For full-text search
        }
        
        # Add only user-defined metadata (not system fields)
        user_metadata = memory_data.get("metadata", {})
        payload["metadata"] = serialize_datetime(user_metadata) if user_metadata else {}
        
        # Add any extra fields (excluding system fields and embedding)
        excluded_fields = ["id", "content", "data", "user_id", "agent_id", "run_id", "metadata", "filters", 
                          "created_at", "updated_at", "actor_id", "hash", "category", "embedding"]
        for key, value in memory_data.items():
            if key not in excluded_fields:
                payload[key] = serialize_datetime(value)
        
        # Insert and get auto-generated ID
        generated_ids = self.vector_store.insert([vector], [payload])
        if not generated_ids:
            raise ValueError("Failed to insert memory: no ID returned from vector store")
        memory_id = generated_ids[0]  # Get the first (and only) generated ID
        return memory_id
    
    def search_memories(
        self,
        query_embedding: List[float],
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
        run_id: Optional[str] = None,
        filters: Optional[Dict[str, Any]] = None,
        limit: int = 30,
        query: Optional[str] = None,
    ) -> List[Dict[str, Any]]:
        """Search for memories."""
        # Use the provided query embedding or generate one
        if query_embedding:
            query_vector = query_embedding
        else:
            # If no query embedding provided, we can't search meaningfully
            logger.warning("No query embedding provided for search")
            return []
        
        # Merge user_id/agent_id/run_id into filters to ensure consistency
        # This ensures filters are applied at the database level, avoiding redundant filtering
        effective_filters = filters.copy() if filters else {}
        if user_id is not None:
            effective_filters["user_id"] = user_id
        if agent_id is not None:
            effective_filters["agent_id"] = agent_id
        if run_id is not None:
            effective_filters["run_id"] = run_id
        
        # Unified search method - try OceanBase format first, fallback to SQLite
        # Pass query text to enable hybrid search (vector + full-text search)
        try:
            # Try OceanBase format first - pass query text for hybrid search
            search_query = query if query else ""
            results = self.vector_store.search(search_query, vectors=query_vector, limit=limit, filters=effective_filters)
        except TypeError:
            # Fallback to SQLite format (doesn't support query text parameter)
            # Still pass filters for SQLite
            results = self.vector_store.search(query_vector, vectors=[query_vector], limit=limit, filters=effective_filters)
        
        # Convert results to unified format
        memories = []
        for result in results:
            # Handle different result formats
            if hasattr(result, 'payload') and result.payload:
                # Result with payload attribute
                payload = result.payload
                memory_id = result.id
                # Extract score - use 0.0 as default instead of 1.0 to avoid false high scores
                # Score should always exist from vector search, but handle None case gracefully
                score = getattr(result, 'score', None)
                if score is None:
                    logger.warning(f"Result {memory_id} missing score, using 0.0")
                    score = 0.0
            elif hasattr(result, 'payload') and isinstance(result.payload, dict):
                # Result with dict payload
                payload = result.payload
                memory_id = result.id
                # Extract score - use 0.0 as default instead of 1.0
                score = getattr(result, 'score', None)
                if score is None:
                    logger.warning(f"Result {memory_id} missing score, using 0.0")
                    score = 0.0
            elif isinstance(result, dict):
                # Direct dict result
                payload = result
                memory_id = result.get("id")
                # Extract score - use 0.0 as default instead of 1.0
                score = result.get("score")
                if score is None:
                    logger.warning(f"Result {memory_id} missing score, using 0.0")
                    score = 0.0
            else:
                continue
            
            # Extract unified fields
            # Core and promoted keys that should not be in metadata
            promoted_payload_keys = ["user_id", "agent_id", "run_id", "actor_id", "role"]
            core_and_promoted_keys = {"data", "hash", "created_at", "updated_at", "id", "metadata", *promoted_payload_keys}
            
            # Extract core fields
            content = payload.get("data", "")
            created_at = payload.get("created_at")
            updated_at = payload.get("updated_at")
            
            # Extract promoted fields
            promoted_fields = {}
            for key in promoted_payload_keys:
                if key in payload:
                    promoted_fields[key] = payload[key]
            
            # Extract user metadata from payload
            # If payload contains "metadata" field (nested user metadata), use it directly
            # Otherwise, extract additional metadata from other fields
            if "metadata" in payload:
                user_metadata = payload["metadata"]
            else:
                # Extract additional metadata (all fields not in core_and_promoted_keys)
                user_metadata = {k: v for k, v in payload.items() if k not in core_and_promoted_keys}
            
            memory = {
                "id": memory_id,
                "memory": content, 
                "created_at": created_at,
                "updated_at": updated_at,
                "score": score,
                **promoted_fields,  # Add promoted fields at top level
                "metadata": user_metadata if user_metadata else {},  # Add user metadata
            }
            
            # Apply filters (as double-check if database didn't filter)
            # Even if filters were applied at database level, apply them here as a safety measure
            if user_id and memory.get("user_id") != user_id:
                continue
            if agent_id and memory.get("agent_id") != agent_id:
                continue
            if run_id and memory.get("run_id") != run_id:
                continue
            
            memories.append(memory)
        
        # Vector store already applied limit, no need to slice again
        return memories
    
    def get_memory(
        self,
        memory_id: int,
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """Get a specific memory by ID."""
        result = self.vector_store.get(memory_id)
        
        if result and result.payload:
            memory = {
                "id": result.id,
                "memory": result.payload.get("data", ""),  # Use 'memory' field name for consistency
                "user_id": result.payload.get("user_id"),
                "agent_id": result.payload.get("agent_id"),
                "run_id": result.payload.get("run_id"),
                "metadata": result.payload.get("metadata", {}),
                "created_at": result.payload.get("created_at"),
                "updated_at": result.payload.get("updated_at"),
            }
            
            # Check access control
            if user_id and memory.get("user_id") != user_id:
                return None
            if agent_id and memory.get("agent_id") != agent_id:
                return None
            
            return memory
        
        return None
    
    def update_memory(
        self,
        memory_id: int,
        update_data: Dict[str, Any],
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """Update a memory with access control checks."""
        # Get existing record and check access control
        existing = self.get_memory(memory_id, user_id, agent_id)
        if not existing:
            logger.warning(f"Memory {memory_id} not found or access denied (user_id={user_id}, agent_id={agent_id})")
            return None
        
        # Get existing payload from vector store
        existing_result = self.vector_store.get(memory_id)
        if not existing_result or not existing_result.payload:
            logger.warning(f"Memory {memory_id} not found in vector store")
            return None
        
        # Get existing payload
        existing_payload = existing_result.payload
        
        # Merge update_data into payload
        updated_payload = existing_payload.copy()
        
        # Handle content field - map to "data" in payload
        if "content" in update_data:
            updated_payload["data"] = update_data["content"]
            updated_payload["fulltext_content"] = update_data["content"]
            # Remove content from update_data to avoid confusion
            update_data = update_data.copy()
            del update_data["content"]
        
        # Serialize datetime objects in update_data before merging
        serialized_update_data = serialize_datetime(update_data)
        
        # Update other fields
        updated_payload.update(serialized_update_data)
        
        # Ensure datetime fields are serialized as ISO format strings
        if "updated_at" in updated_payload:
            updated_at = updated_payload["updated_at"]
            if isinstance(updated_at, datetime):
                updated_payload["updated_at"] = updated_at.isoformat()
        if "created_at" in updated_payload:
            created_at = updated_payload["created_at"]
            if isinstance(created_at, datetime):
                updated_payload["created_at"] = created_at.isoformat()
        
        # Update updated_at if not provided
        if "updated_at" not in updated_payload:
            updated_payload["updated_at"] = datetime.utcnow().isoformat()
        
        # Update in vector store with proper payload
        self.vector_store.update(memory_id, vector=update_data.get("embedding"), payload=updated_payload)
        
        return updated_payload
    
    def delete_memory(
        self,
        memory_id: int,
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
    ) -> bool:
        """Delete a memory."""
        # Check if memory exists and user has access
        existing = self.get_memory(memory_id, user_id, agent_id)
        if not existing:
            return False
        
        # Delete from vector store
        self.vector_store.delete(memory_id)
        return True
    
    def get_all_memories(
        self,
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
        run_id: Optional[str] = None,
        limit: int = 100,
        offset: int = 0,
    ) -> List[Dict[str, Any]]:
        """Get all memories with optional filtering."""
        # Build filters for database-level filtering
        filters = {}
        if user_id:
            filters["user_id"] = user_id
        if agent_id:
            filters["agent_id"] = agent_id
        if run_id:
            filters["run_id"] = run_id
        
        # Get memories from vector store with filters (if supported)
        if filters and hasattr(self.vector_store, 'list'):
            # Pass filters to vector store's list method for database-level filtering
            # Request more records to support offset
            results = self.vector_store.list(filters=filters, limit=limit + offset)
        else:
            # Fallback: get all and filter in memory
            results = self.vector_store.list(limit=limit + offset)
        
        # OceanBase returns [memories], SQLite/PGVector return memories directly
        if results and isinstance(results[0], list):
            raw_results = results[0]
        else:
            raw_results = results
        
        # Convert to expected format and apply filters
        memories = []
        for result in raw_results:
            # Handle different result formats
            if hasattr(result, 'payload') and result.payload:
                # Result with payload attribute (e.g., from OceanBase OutputData)
                payload = result.payload
                memory_id = result.id
            elif isinstance(result, dict):
                # Direct dict result (e.g., from SQLite)
                payload = result
                memory_id = result.get("id")
            else:
                continue
            
            # Convert datetime objects to ISO format strings
            created_at = payload.get("created_at")
            if created_at is not None:
                from datetime import datetime
                if isinstance(created_at, datetime):
                    created_at = created_at.isoformat()
            
            updated_at = payload.get("updated_at")
            if updated_at is not None:
                from datetime import datetime
                if isinstance(updated_at, datetime):
                    updated_at = updated_at.isoformat()
            
            memory = {
                "id": memory_id,
                "memory": payload.get("data", ""),  # Extract from "data" field, return as "memory"
                "user_id": payload.get("user_id"),
                "agent_id": payload.get("agent_id"),
                "run_id": payload.get("run_id"),
                "metadata": payload.get("metadata", {}),
                "created_at": created_at,
                "updated_at": updated_at,
            }
            
            # Apply filters (as double-check if database didn't filter)
            # Note: If filters were applied at database level, these will all pass
            if user_id and memory.get("user_id") != user_id:
                continue
            if agent_id and memory.get("agent_id") != agent_id:
                continue
            if run_id and memory.get("run_id") != run_id:
                continue
            
            memories.append(memory)
        
        # Apply offset and limit
        return memories[offset:offset + limit]
    
    def clear_memories(
        self,
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
        run_id: Optional[str] = None,
    ) -> bool:
        """Clear all memories for a user or agent or run."""
        # Build filters for database query
        filters = {}
        if user_id:
            filters["user_id"] = user_id
        if agent_id:
            filters["agent_id"] = agent_id
        if run_id:
            filters["run_id"] = run_id
        
        # Use batch processing to avoid timeout
        batch_size = 1000
        deleted_count = 0
        
        while True:
            # Get a batch of memories with filtering
            batch = self.get_all_memories(user_id, agent_id, run_id, limit=batch_size, offset=deleted_count)
            
            # If no more records, we're done
            if not batch:
                break
            
            # Delete each memory in the batch
            for memory in batch:
                try:
                    self.vector_store.delete(memory["id"])
                except Exception as e:
                    logger.warning(f"Failed to delete memory {memory.get('id')}: {e}")
            
            deleted_count += len(batch)
            
            # If we got fewer records than batch_size, we've reached the end
            if len(batch) < batch_size:
                break
        
        logger.info(f"Deleted {deleted_count} memories with filters: {filters}")
        return True
    
    async def get_all_memories_async(
        self,
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
        run_id: Optional[str] = None,
        limit: int = 100,
        offset: int = 0,
    ) -> List[Dict[str, Any]]:
        """Get all memories with optional filtering asynchronously."""
        import asyncio
        return await asyncio.to_thread(self.get_all_memories, user_id, agent_id, run_id, limit, offset)
    
    async def clear_memories_async(
        self,
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
        run_id: Optional[str] = None,
    ) -> bool:
        """Clear all memories for a user or agent or run asynchronously."""
        import asyncio
        return await asyncio.to_thread(self.clear_memories, user_id, agent_id, run_id)
    
    async def initialize_async(self):
        """Initialize storage asynchronously."""
        # No-op for now
        pass
    
    async def add_memory_async(self, memory_data: Dict[str, Any]) -> int:
        """Add a memory to the store asynchronously."""
        import asyncio
        return await asyncio.to_thread(self.add_memory, memory_data)
    
    async def search_memories_async(
        self,
        query_embedding: List[float],
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
        run_id: Optional[str] = None,
        filters: Optional[Dict[str, Any]] = None,
        limit: int = 30,
        query: Optional[str] = None,
    ) -> List[Dict[str, Any]]:
        """Search for memories asynchronously."""
        import asyncio
        return await asyncio.to_thread(self.search_memories, query_embedding, user_id, agent_id, run_id, filters, limit, query)
    
    async def get_memory_async(
        self,
        memory_id: int,
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """Get a specific memory by ID asynchronously."""
        import asyncio
        return await asyncio.to_thread(self.get_memory, memory_id, user_id, agent_id)
    
    async def delete_memory_async(
        self,
        memory_id: int,
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
    ) -> bool:
        """Delete a memory asynchronously."""
        import asyncio
        return await asyncio.to_thread(self.delete_memory, memory_id, user_id, agent_id)
    
    async def update_memory_async(
        self,
        memory_id: int,
        update_data: Dict[str, Any],
        user_id: Optional[str] = None,
        agent_id: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """Update a memory asynchronously."""
        import asyncio
        return await asyncio.to_thread(self.update_memory, memory_id, update_data, user_id, agent_id)
